package com.example.travel.region.domain;

public enum RegionType {

	SPECIAL_CITY,
	METROPOLITAN_CITY,
	SPECIAL_SELF_GOVERNING_CITY,
	PROVINCE,
	SPECIAL_SELF_GOVERNING_PROVINCE,
	INTEGRATED_SPECIAL_CITY,
	CITY,
	COUNTY,
	DISTRICT_FILTER,
	COUNTY_FILTER
}
